{% set name = "afm" %}
{% set version = "1.0.0" %}
{% set hash = "5bd4d6f6241e7014ef090985ec6f4c3e9745f6de0828ddd58bc1efdd138f4545" %}
{% set build = 2 %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: {{ hash }}

build:
  noarch: generic
  number: {{ build }}
  script:
    - gem install -N -l -V --norc --ignore-dependencies -n $PREFIX/bin {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}

test:
  commands:
    - ruby -r afm -e 'exit 0'

about:
  home: https://rubygems.org/gems/afm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a simple library to read afm files and use the data conveniently.

  doc_url: https://www.rubydoc.info/gems/afm
  dev_url: https://github.com/halfbyte/afm

extra:
  recipe-maintainers:
    - ajaypnair09
    - rudispr
